[{"link":"https://www.mediafire.com/file/07seesj1hmnxx2l/203.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/founddie.com-2-2.jpg",
"title":"ဆေးခပ်ပြီးဘုတာလားမသိဘူး",
"info":"",
"time":"4min"},
{"link":"https://www.mediafire.com/file/07seesj1hmnxx2l/203.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/founddie.com-38-1.jpg",
"title":"အထည်ချုပ်ကခိုင်ဇင်၀င်းကုန်းတာလေးအပိုင်း (၁)",
"info":"",
"time":"6min"},
{"link":"https://www.mediafire.com/file/qkoisphp5wk9mau/001.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/founddie-%E1%80%96%E1%80%B1%E1%80%AC%E1%80%84%E1%80%BA%E1%80%B8%E1%80%92%E1%80%AD%E1%80%AF%E1%80%84%E1%80%BA%E1%80%B8-20.jpeg",
"title":"TikTokမှာထုပြတဲ့ဆော်တွေလောက်",
"info":"TikTokမှာထုပြတဲ့ဆော်တွေလောက်တော့သနားတယ်",
"time":""},
{"link":"https://www.mediafire.com/file/4ir0g2h5snflsaw/002.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Scrdkdm.jpg",
"title":"မြန်မာဝမ်းဆက်နဲ့ ဆော်လေး",
"info":"ချောင်းရိုက်",
"time":""},
{"link":"https://www.mediafire.com/file/opc02cmuc7fdxzo/003.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1644497437-picsay.jpg",
"title":"ခြေနှစ်ချောင်း ပုခုံးပေါ်တင်ပြီး ရှယ်ဆောင့်",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/y1zm70fuw4nrq5z/video090222b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1644379915-picsay.jpg",
"title":"အကွက်ပေါင်းစုံဆွဲတဲ့ အတွဲ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/e1giig2buu3hagf/video110222c.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1639750387-picsay.jpg",
"title":"ဆော်က တော်ပြီပြောတာကို",
"info":"ဆော်က တော်ပြီပြောတာကို ပြီးအောင် စုပ်ခိုင်းတဲ့ ဘဲကြီး",
"time":""},
{"link":"https://www.mediafire.com/file/lx45p98rthkkr61/video120122b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1641974530-picsay.jpg",
"title":"ချစ်လို့ ပုလွေပေး",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/93i3yk12qvei8a2/video3122c.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Scrfkfk.jpg",
"title":"ကိုတုတ်ကြီးကို ချစ်တယ်တဲ့",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/6wamtvq339jxnb0/video070222a.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1644209964-picsay.jpg",
"title":"ရှယ်ပြုစုပြီးမှ လိုးကြတဲ့အတွဲ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/xbuk3a3dc2iqc8y/video170122i.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1642425162-picsay.jpg",
"title":"လီးစုပ်ပေးတာလေး မိုက်မှမိုက်",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/66ue2ezoujvecdc/video260122e.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1643190770-picsay.jpg",
"title":"လိုးချင်စရာ စောက်ဖုတ်လေး",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/x68c10ksjldthp1/video030222d.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1643896861-picsay.jpg",
"title":"ဆော်လေး ရှက်နေတာ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/9gz4goqqo80mein/video080122b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1641607288-picsay.jpg",
"title":"ဘော်ဒီကြီးကတော့ ရှယ်ပဲ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/qjsf0bchhl9wlma/video020222b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1643795536-picsay.jpg",
"title":"မျက်နှာပေါ်မှာပြီးတဲ့ မြန်မာပြည်က",
"info":"မျက်နှာပေါ်မှာပြီးတဲ့ မြန်မာပြည်က ကုလားမလေး",
"time":""},
{"link":"https://www.mediafire.com/file/vcd8uq0bgmqdh5w/video240122b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1643000585-picsay.jpg",
"title":"ဆောင့်လေ ဆောင့်တဲ့",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/f0662ure4ixuyco/nov1621a.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/fjvv.jpg",
"title":"အမြဲတမ်းလိုးပေးမယ်တဲ့",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/434iw7mkotevs1l/video220122a.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1642836845-picsay.jpg",
"title":"နည်းတဲ့အိုးကြီးလား",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/0asnaset64fiqjf/video140122b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Scdkdnn.jpg",
"title":"အပြုအစုကျွမ်းတဲ့ မြန်မာမလေး",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/2okmmmivvm4ph63/video130122b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1642040711-picsay.jpg",
"title":"ကျွန်တော့်ရဲ့ မိန်းမလေးပါတဲ့",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/8ao7xobjxwu861y/%25E1%2580%259C%25E1%2580%25AE%25E1%2580%25B8%25E1%2580%2599%25E1%2580%25B2%25E1%2580%2580%25E1%2580%25BC%25E1%2580%25AE%25E1%2580%25B8.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/%E1%80%9C%E1%80%AE%E1%80%B8%E1%80%99%E1%80%B2%E1%80%80%E1%80%BC%E1%80%AE%E1%80%B8_thumb1.jpg",
"title":"လီးမဲကြီ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/r3vm2lg0iy731ha/တအားတွေဖြစ်နေတာ+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-37.jpg",
"title":"တအားတွေဖြစ်နေတာ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/au7sq81otvpdc04/185.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/BeFunky-collage-12-1.jpg",
"title":"အငြိမ်လေး",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/p4rkj57k9zoizh7/အော်သာအော်တယ်ကောင်းသွားတာ+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-18-1.jpg",
"title":"အော်သာအော်တယ်ကောင်းသွားတာ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/lll003rzhtgksnk/လန်ထွက်နေတဲ့အပိုင်း+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-15-1.jpg",
"title":"လန်ထွက်နေတဲ့အပိုင်း",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/es70somlp8151av/TikTokကဆယ်လီမလေး+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-17.jpg",
"title":"TikTokကဆယ်လီမလေး",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/sufxz7zrewxl8k9/ဧကရီရဲ့+အိုးအကိတ်ကြီး+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-64.jpg",
"title":"ဧကရီရဲ့ အိုးအကိတ်ကြီး",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/v1c6m4efatt7apc/ထမိန်လှန်ပြီးမော်တော်ဆပ်+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-53.jpg",
"title":"ထမိန်လှန်ပြီးမော်တော်ဆပ်",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/t65n6i1r7ebd9bf/ဒဂုံဆိပ်ကမ်း+Nestle+Factoryကဆော်ကြီးပေးချက်+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-48.jpg",
"title":"ဒဂုံဆိပ်ကမ်း Nestle Factory",
"info":"ဒဂုံဆိပ်ကမ်း Nestle Factoryကဆော်ကြီးပေးချက်",
"time":""},
{"link":"https://www.mediafire.com/file/4xxhuqyt4yyqldb/ဆော်လေးကရှက်နေတာ+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-46.jpg",
"title":"ဆော်လေးကရှက်နေတာ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/17stuk1xfeilwps/ဆော်ကတကယ်တင်းနေတာ+.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Founddie.com-45.jpg",
"title":"ဆော်ကတကယ်တင်းနေတာ",
"info":"",
"time":""}]
