[{"link":"https://www.mediafire.com/file/07seesj1hmnxx2l/203.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/founddie.com-2-2.jpg",
"title":"ဆေးခပ်ပြီးဘုတာလားမသိဘူး",
"info":"",
"time":"4min"},
{"link":"https://www.mediafire.com/file/07seesj1hmnxx2l/203.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/founddie.com-38-1.jpg",
"title":"အထည်ချုပ်ကခိုင်ဇင်၀င်းကုန်းတာလေးအပိုင်း (၁)",
"info":"",
"time":"6min"},
{"link":"https://www.mediafire.com/file/qkoisphp5wk9mau/001.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/founddie-%E1%80%96%E1%80%B1%E1%80%AC%E1%80%84%E1%80%BA%E1%80%B8%E1%80%92%E1%80%AD%E1%80%AF%E1%80%84%E1%80%BA%E1%80%B8-20.jpeg",
"title":"TikTokမှာထုပြတဲ့ဆော်တွေလောက်",
"info":"TikTokမှာထုပြတဲ့ဆော်တွေလောက်တော့သနားတယ်",
"time":""},
{"link":"https://www.mediafire.com/file/4ir0g2h5snflsaw/002.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/Scrdkdm.jpg",
"title":"မြန်မာဝမ်းဆက်နဲ့ ဆော်လေး",
"info":"ချောင်းရိုက်",
"time":""},
{"link":"https://www.mediafire.com/file/opc02cmuc7fdxzo/003.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1644497437-picsay.jpg",
"title":"ခြေနှစ်ချောင်း ပုခုံးပေါ်တင်ပြီး ရှယ်ဆောင့်",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/y1zm70fuw4nrq5z/video090222b.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1644379915-picsay.jpg",
"title":"အကွက်ပေါင်းစုံဆွဲတဲ့ အတွဲ",
"info":"",
"time":""},
{"link":"https://www.mediafire.com/file/e1giig2buu3hagf/video110222c.mp4/file",
"image":"https://raw.githubusercontent.com/shawlin247/mmphoto/main/1639750387-picsay.jpg",
"title":"ဆော်က တော်ပြီပြောတာကို",
"info":"ဆော်က တော်ပြီပြောတာကို ပြီးအောင် စုပ်ခိုင်းတဲ့ ဘဲကြီး",
"time":""}]
